### ISSUE TITLE
Consider using Markdown for better readability

### ISSUE THREAD

**Issue by Dimava** [GoofGarage/Win11Clean#7]
While txts may be more easy to open on a PC, reading Markdown in Github web UI is much better experience then reading txt files here

**Comment by GoofGarage** [comment]
Agreed.  Adding to the 2024-January release, which should be on or around 2024-01-15.

**Comment by GoofGarage** [comment]
Guide converted to Markdown for 0.4 release as requested.  Closing as resolved.
